version: "3"

services:
  app:
    container_name: ecotria_client
    build:
      context: .
      dockerfile: DockerFile
    restart: unless-stopped
    environment:
      - ./.env
    volumes:
      - ./:/app/
    ports:
      - 3000:3000
    command: "http-server ./dist -p 3000"
volumes:
# networks:
#   ecotria-net:
#     driver: bridge
