import React from "react";
import InfiniteScroll from "react-infinite-scroller";
import { useInfiniteQuery } from "@tanstack/react-query";

import Postview from "../components/Postview";
import Load from "../components/Load";

import { useAuth } from "../context/ContextAuth";

import api from "../services";
import { ProductDetail } from "../models/Product";

// Generated by https://quicktype.io

export interface Pagination {
  data: ProductDetail[] | null;
  total: number;
  page: number;
  limit: number;
  message: string;
}

const Home = () => {
  const { token } = useAuth();
  const { data, isLoading, fetchNextPage, hasNextPage } = useInfiniteQuery<Pagination>(
    ["productos"],
    ({ signal, pageParam = 1 }) =>
      api.productos.getProductsByPage({ signal, token: String(token), page: pageParam }),

    {
      getNextPageParam: (lastPage, pages) => {
        if (pages?.length === 0 || pages == null) return false;
        return lastPage.page + 1;
      },
    }
  );

  const products =
    data?.pages.reduce(
      (prevProducts, page) => (page.data ? prevProducts.concat(page.data) : prevProducts),
      []
    ) ?? [];

  console.log(products);
  return (
    <div className="main-content right-chat-active">
      <div className="middle-sidebar-bottom">
        <div className="middle-sidebar-left">
          <div className="row feed-body">
            <div className="col-xl-8 col-xxl-9 col-lg-8">
              {/* <InfiniteScroll
                pageStart={1}
                loadMore={() => fetchNextPage()}
                hasMore={hasNextPage || isLoading}
                loader={<Load />}
              >
     
              </InfiniteScroll> */}
              {products.length > 0 ? (
                products.map((producto: ProductDetail) => (
                  <Postview
                    key={producto._id}
                    id={producto._id}
                    postvideo=""
                    postimage={producto.Images?.length ? producto.Images[0] : "https://picsum.photos/800/450"}
                    avatar={producto.Images?.length ? producto.Images[0] : "https://picsum.photos/100/100"}
                    title={producto.titlePost}
                    time={producto.createDate}
                    description={producto.descriptionPost}
                  />
                ))
              ) : (
                <div></div>
              )}
            </div>
            {/* <div className="col-xl-4 col-xxl-3 col-lg-4 ps-lg-0">
              <Friends />
              <Contacts />
              <Group />
              <Events />
              <Profilephoto />
            </div> */}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
